const API_BASE_URL = 'http://localhost:8080';

export default {
    API_BASE_URL: API_BASE_URL,
    API_ROOT: `${API_BASE_URL}/api`,
    BLOGS: 'blogs',
    BLOG_BLOCKINGS: 'blog-blockings',
    GLOBAL_BLOCKINGS: 'global-blockings',
    BLOG_POSTS: 'blog-posts',
    BLOG_POST_LIKES: 'blog-post-likes',
    BLOG_POST_REPORTS: 'blog-post-reports',
    COMMENTS: 'comments',
    COMMENT_LIKES: 'comment-likes',
    COMMENT_REPORTS: 'comment-reports',
    LIKES: 'likes',
    REPORTS: 'reports',
    NOTIFICATIONS: 'notifications',
    NOT_READ_NOTIFICATIONS: 'notifications/new',
    REPLIES: 'replies',
    OAUTH: 'oauth',
    TOKEN: 'token',
    REVOKE_TOKEN: 'revoke-token',
    USERS: 'users',
    CURRENT_USER: 'users/current',
    USERNAME: 'username',
    IS_AVAILABLE: 'is-available',
    SUBSCRIBERS: 'subscribers',
    SUBSCRIPTIONS: 'subscriptions',
    FULL_PROFILE: 'full-profile',
    MANAGERS: 'managers',
    OWNER: 'owner',
    MARK_READ: 'mark-read',
    MARK_UNREAD: 'mark-unread'
};