export const WEB_APP_BASE_URL = process.env.REACT_APP_WEB_APP_BASE_URL;
const API_BASE_URL = process.env.REACT_APP_API_BASE_URL;

export default {
    API_BASE_URL: API_BASE_URL,
    API_ROOT: `${API_BASE_URL}/api`,
    WEB_SOCKET_API_ROOT: `${API_BASE_URL}/api/web-socket`,
    BLOGS: 'blogs',
    BLOG_BLOCKINGS: 'blog-blockings',
    GLOBAL_BLOCKINGS: 'global-blockings',
    BLOG_POSTS: 'blog-posts',
    BLOG_POST_LIKES: 'blog-post-likes',
    BLOG_POST_REPORTS: 'blog-post-reports',
    COMMENTS: 'comments',
    THREAD: 'thread',
    COMMENT_LIKES: 'comment-likes',
    COMMENT_REPORTS: 'comment-reports',
    LIKES: 'likes',
    REPORTS: 'reports',
    NOTIFICATIONS: 'notifications',
    NOT_READ_NOTIFICATIONS: 'notifications/new',
    REPLIES: 'replies',
    OAUTH: 'oauth',
    TOKEN: 'token',
    REVOKE_TOKEN: 'revoke-token',
    USERS: 'users',
    CURRENT_USER: 'users/current',
    USERNAME: 'username',
    IS_AVAILABLE: 'is-available',
    SUBSCRIBERS: 'subscribers',
    SUBSCRIPTIONS: 'subscriptions',
    FULL_PROFILE: 'full-profile',
    MANAGERS: 'managers',
    OWNER: 'owner',
    MARK_READ: 'mark-read',
    MARK_UNREAD: 'mark-unread',
    NOT_ENDED: 'not-ended',
    MINIFIED: 'minified',
    CREATED: 'created',
    AUTHOR: 'author',
    FEED: 'feed',
    BLOCKINGS: 'blockings',
    GOOGLE: 'google',
    OWNED_BLOGS: 'owned-blogs',
    MOST_POPULAR: 'most-popular',
    FOR_WEEK: 'for-week',
    FOR_MONTH: 'for-month',
    FOR_YEAR: 'for-year',
    PIN: 'pin',
    UNPIN: 'unpin',
    PINNED: 'pinned',
    USER: 'user',
    HANDSHAKE: 'handshake',
    SEARCH: 'search'
};